### ISSUE TITLE
Kaitai Structを使ってみる

### ISSUE THREAD

**Issue by hangingman** [hangingman/wxMMDViewer#1]
ref https://kaitai.io
ref https://github.com/hangingman/mmd-lwjgl

## Kaitai Structについて
- Kaitai Structはクロスプラットフォームなバイナリパーサーで、パース対象のバイナリ構造をYAMLで書くとパーサーを自動生成してくれる 

以下のような感じで書ける
- ユーザーガイド: https://doc.kaitai.io/user_guide.html

```yaml
types:
  header:
    seq:
      - id: magic
        contents: 'Pmd'
      - id: version
        type: f4  <-- float 4byteの意
      - id: model_name
        type: strz  <-- strz(=string zero) null terminated (0x00終わり)のstring
        size: 20
        encoding: Shift_JIS  <-- C++だとiconv連携して文字コード変換できる（to UTF-8）
      - id: comment
        type: strz
        size: 256
        encoding: Shift_JIS
```

- 型定義
  - 構造体を定義してYAMLの中で使える
  - `4.7. Substructures (subtypes)`

```yaml
seq:
  - id: track_title
    type: str_with_len
  - id: album_title
    type: str_with_len
  - id: artist_name
    type: str_with_len
types:
  str_with_len:
    seq:
      - id: len
        type: u4
      - id: value
        type: str
        encoding: UTF-8
        size: len
```
